hospitals = [
    {
      "name": "Sunrise Clinic",
      "address": "Link Road, Cuttack, Odisha 753014, India",
      "phone": "+91 671 235 5678",
      "email": "info@sunriseclinic.com",
      "lat": 20.476821,
      "lng": 85.865956,
      "url": "https://www.sunriseclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Cuttack",
      "zip": 753014
    },
    {
      "name": "Wellness Clinic",
      "address": "Mahanadi Vihar, Cuttack, Odisha 753004, India",
      "phone": "+91 671 236 7890",
      "email": "info@wellnessclinic.com",
      "lat": 20.473015,
      "lng": 85.847283,
      "url": "https://www.wellnessclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Cuttack",
      "zip": 753004
    },
    {
      "name": "City Care Clinic",
      "address": "Ring Road, Cuttack, Odisha 753012, India",
      "phone": "+91 671 236 2345",
      "email": "info@citycareclinic.com",
      "lat": 20.456745,
      "lng": 85.858441,
      "url": "https://www.citycareclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Cuttack",
      "zip": 753012
    },
    {
      "name": "Heal Clinic",
      "address": "Sahid Nagar, Bhubaneswar, Odisha 751007, India",
      "phone": "+91 674 254 6789",
      "email": "info@healclinic.com",
      "lat": 20.293712,
      "lng": 85.832375,
      "url": "https://www.healclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751007
    },
    {
      "name": "Arogya Clinic",
      "address": "IRC Village, Nayapalli, Bhubaneswar, Odisha 751015, India",
      "phone": "+91 674 256 2345",
      "email": "info@arogyaclinic.com",
      "lat": 20.305029,
      "lng": 85.812303,
      "url": "https://www.arogyaclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751015
    },
    {
      "name": "MediHealth Clinic",
      "address": "Patia, Bhubaneswar, Odisha 751024, India",
      "phone": "+91 674 273 4567",
      "email": "info@medihealthclinic.com",
      "lat": 20.346017,
      "lng": 85.828387,
      "url": "https://www.medihealthclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751024
    },
    {
      "name": "Life Care Clinic",
      "address": "Rasulgarh, Bhubaneswar, Odisha 751010, India",
      "phone": "+91 674 255 6789",
      "email": "info@lifecareclinic.com",
      "lat": 20.311517,
      "lng": 85.844061,
      "url": "https://www.lifecareclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751010
    },
    {
      "name": "Greenview Clinic",
      "address": "Jayadev Vihar, Bhubaneswar, Odisha 751013, India",
      "phone": "+91 674 256 1234",
      "email": "info@greenviewclinic.com",
      "lat": 20.305241,
      "lng": 85.830564,
      "url": "https://www.greenviewclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751013
    },
    {
      "name": "CarePlus Clinic",
      "address": "Acharya Vihar, Bhubaneswar, Odisha 751013, India",
      "phone": "+91 674 257 8901",
      "email": "info@careplusclinic.com",
      "lat": 20.302492,
      "lng": 85.819163,
      "url": "https://www.careplusclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751013
    },
    {
      "name": "Metro Clinic",
      "address": "Janpath, Bhubaneswar, Odisha 751001, India",
      "phone": "+91 674 256 7890",
      "email": "info@metroclinic.com",
      "lat": 20.266001,
      "lng": 85.841556,
      "url": "https://www.metroclinic.com/",
      "country": "India",
      "state": "Odisha",
      "city": "Bhubaneswar",
      "zip": 751001
    },
    {
        "name": "Care Clinic",
        "address": "Ring Road, Cuttack, Odisha 753012, India",
        "phone": "+91 671 236 1346",
        "email": "info@careclinic.com",
        "lat": 20.456745,
        "lng": 85.858441,
        "url": "https://www.careclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753012
      },
      {
        "name": "Hope Clinic",
        "address": "Link Road, Cuttack, Odisha 753014, India",
        "phone": "+91 671 235 5678",
        "email": "info@hopeclinic.com",
        "lat": 20.476821,
        "lng": 85.865956,
        "url": "https://www.hopeclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753014
      },
      {
        "name": "Sunrise Clinic",
        "address": "Buxi Bazaar, Cuttack, Odisha 753001, India",
        "phone": "+91 671 231 6789",
        "email": "info@sunriseclinic.com",
        "lat": 20.465772,
        "lng": 85.879294,
        "url": "https://www.sunriseclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753001
      },
      {
        "name": "Care 'n Cure Clinic",
        "address": "Nayapalli, Bhubaneswar, Odisha 751015, India",
        "phone": "+91 674 255 3456",
        "email": "info@carenccureclinic.com",
        "lat": 20.305572,
        "lng": 85.828966,
        "url": "https://www.carencureclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751015
      },
      {
        "name": "Heal Clinic",
        "address": "Saheed Nagar, Bhubaneswar, Odisha 751007, India",
        "phone": "+91 674 254 6789",
        "email": "info@healclinic.com",
        "lat": 20.293712,
        "lng": 85.832375,
        "url": "https://www.healclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751007
      },
      {
        "name": "MediCare Clinic",
        "address": "Rasulgarh, Bhubaneswar, Odisha 751010, India",
        "phone": "+91 674 256 7890",
        "email": "info@medicareclinic.com",
        "lat": 20.311517,
        "lng": 85.844061,
        "url": "https://www.medicareclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751010
      },
      {
        "name": "City Clinic",
        "address": "Kalpana Square, Bhubaneswar, Odisha 751014, India",
        "phone": "+91 674 253 4567",
        "email": "info@cityclinic.com",
        "lat": 20.265311,
        "lng": 85.822135,
        "url": "https://www.cityclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751014
      },
      {
        "name": "Sunshine Clinic",
        "address": "IRC Village, Nayapalli, Bhubaneswar, Odisha 751015, India",
        "phone": "+91 674 254 7890",
        "email": "info@sunshineclinic.com",
        "lat": 20.305029,
        "lng": 85.812303,
        "url": "https://www.sunshineclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751015
      },
      {
        "name": "Greenview Clinic",
        "address": "Jayadev Vihar, Bhubaneswar, Odisha 751013, India",
        "phone": "+91 674 256 1234",
        "email": "info@greenviewclinic.com",
        "lat": 20.305241,
        "lng": 85.830564,
        "url": "https://www.greenviewclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751013
      },
      {
        "name": "Life Care Clinic",
        "address": "Acharya Vihar, Bhubaneswar, Odisha 751013, India",
        "phone": "+91 674 257 8901",
        "email": "info@lifecareclinic.com",
        "lat": 20.303758,
        "lng": 85.822895,
        "url": "https://www.lifecareclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751013
      },
      {
        "name": "MediPoint Clinic",
        "address": "Sahid Nagar, Bhubaneswar, Odisha 751007, India",
        "phone": "+91 674 254 8901",
        "email": "info@medipointclinic.com",
        "lat": 20.297074,
        "lng": 85.838353,
        "url": "https://www.medipointclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751007
      },
      {
        "name": "Metro Clinic",
        "address": "Janpath, Bhubaneswar, Odisha 751001, India",
        "phone": "+91 674 256 7890",
        "email": "info@metroclinic.com",
        "lat": 20.266001,
        "lng": 85.841556,
        "url": "https://www.metroclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751001
      },
      {
        "name": "Perfect Clinic",
        "address": "Forest Park, Bhubaneswar, Odisha 751009, India",
        "phone": "+91 674 257 8901",
        "email": "info@perfectclinic.com",
        "lat": 20.268035,
        "lng": 85.847888,
        "url": "https://www.perfectclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751009
      },
      {
        "name": "Pulse Clinic",
        "address": "Rasulgarh, Bhubaneswar, Odisha 751010, India",
        "phone": "+91 674 255 8901",
        "email": "info@pulseclinic.com",
        "lat": 20.315178,
        "lng": 85.842009,
        "url": "https://www.pulseclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751010
      },
      {
        "name": "Star Clinic",
        "address": "Jayadev Vihar, Bhubaneswar, Odisha 751013, India",
        "phone": "+91 674 257 4567",
        "email": "info@starclinic.com",
        "lat": 20.302579,
        "lng": 85.829624,
        "url": "https://www.starclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751013
      },
      {
        "name": "Health First Clinic",
        "address": "Sahid Nagar, Bhubaneswar, Odisha 751007, India",
        "phone": "+91 674 254 5678",
        "email": "info@healthfirstclinic.com",
        "lat": 20.296759,
        "lng": 85.833729,
        "url": "https://www.healthfirstclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751007
      },
      {
        "name": "Family Clinic",
        "address": "Acharya Vihar, Bhubaneswar, Odisha 751013, India",
        "phone": "+91 674 257 6789",
        "email": "info@familyclinic.com",
        "lat": 20.302492,
        "lng": 85.819163,
        "url": "https://www.familyclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751013
      },
      {
        "name": "Healthy Living Clinic",
        "address": "Sahid Nagar, Bhubaneswar, Odisha 751007, India",
        "phone": "+91 674 254 1234",
        "email": "info@healthylivingclinic.com",
        "lat": 20.296715,
        "lng": 85.836158,
        "url": "https://www.healthylivingclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751007
      },
      {
        "name": "Sunshine Dispensary",
        "address": "Janpath, Cuttack, Odisha 753001, India",
        "phone": "+91 671 231 9876",
        "email": "info@sunshinedispensary.com",
        "lat": 20.464883,
        "lng": 85.884083,
        "url": "https://www.sunshinedispensary.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753001
      },
      {
        "name": "Relief Dispensary",
        "address": "Badambadi, Cuttack, Odisha 753009, India",
        "phone": "+91 671 237 6543",
        "email": "info@reliefdispensary.com",
        "lat": 20.468009,
        "lng": 85.881993,
        "url": "https://www.reliefdispensary.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753009
      },
      {
        "name": "Care Dispensary",
        "address": "College Square, Cuttack, Odisha 753003, India",
        "phone": "+91 671 258 3456",
        "email": "info@caredispensary.com",
        "lat": 20.469513,
        "lng": 85.888545,
        "url": "https://www.caredispensary.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753003
      },
      {
        "name": "MediServe Dispensary",
        "address": "Buxi Bazaar, Cuttack, Odisha 753001, India",
        "phone": "+91 671 232 3456",
        "email": "info@mediservedispensary.com",
        "lat": 20.463221,
        "lng": 85.883102,
        "url": "https://www.mediservedispensary.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753001
      } ,
      {
        "name": "SCB Medical College and Hospital",
        "address": "Dhamanagar, Cuttack, Odisha 753003, India",
        "phone": "+91 671 258 1000",
        "email": "info@scbmch.ac.in",
        "lat": 20.4833333,
        "lng": 85.7833333,
        "url": "https://www.scbmch.ac.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753003
      },
      {
        "name": "Utkal Hospital",
        "address": "Chandrasekharpur, Cuttack, Odisha 753001, India",
        "phone": "+91 671 230 1333",
        "email": "utkalhospitalcuttack@gmail.com",
        "lat": 20.4916667,
        "lng": 85.7733333,
        "url": "https://www.utkalhospitals.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753001
      },
      {
        "name": "Sun Hospital",
        "address": "Link Road, Cuttack, Odisha 753012, India",
        "phone": "+91 671 230 1333",
        "email": "info@sunhospital.com",
        "lat": 20.4691022,
        "lng": 85.8608598,
        "url": "https://www.sunhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753012
      },
      {
        "name": "Bhubaneswar Hospital Pvt. Ltd.",
        "address": "Kalpana Square, Bhubaneswar, Odisha 751014, India",
        "phone": "+91 674 253 1150",
        "email": "info@bhubaneswarhospital.com",
        "lat": 20.2646583,
        "lng": 85.8175708,
        "url": "https://www.bhubaneswarhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751014
      },
      {
        "name": "Sum Ultimate Medicare",
        "address": "Kalinga Nagar, Bhubaneswar, Odisha 751003, India",
        "phone": "+91 674 235 5888",
        "email": "info@sumultimate.com",
        "lat": 20.296586,
        "lng": 85.8338845,
        "url": "https://www.sumultimate.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751003
      },
      {
        "name": "Kalinga Hospital Limited",
        "address": "Chandrasekharpur, Bhubaneswar, Odisha 751023, India",
        "phone": "+91 674 230 0570",
        "email": "info@kalingahospital.com",
        "lat": 20.3228133,
        "lng": 85.8000413,
        "url": "https://www.kalingahospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751023
      },
      {
        "name": "Apollo Hospitals Bhubaneswar",
        "address": "Plot No: 251, Sainik School Road, Bhubaneswar, Odisha 751005, India",
        "phone": "+91 674 666 1016",
        "email": "contactus@apollobbsr.com",
        "lat": 20.3142216,
        "lng": 85.8492954,
        "url": "https://www.apollohospitals.com/locations/india/bhubaneswar",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751005
      },
      {
        "name": "AIIMS Bhubaneswar",
        "address": "Sijua, Patrapada, Bhubaneswar, Odisha 751019, India",
        "phone": "+91 674 247 6789",
        "email": "director@aiimsbhubaneswar.edu.in",
        "lat": 20.2546233,
        "lng": 85.8166055,
        "url": "https://aiimsbhubaneswar.nic.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751019
      },
      {
        "name": "Aditya Care Hospital",
        "address": "Mahanadi Vihar, Cuttack, Odisha 753004, India",
        "phone": "+91 671 236 1414",
        "email": "info@adityacare.org",
        "lat": 20.4720099,
        "lng": 85.8499583,
        "url": "https://adityacare.org/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753004
      },
      {
        "name": "KIMS Hospital",
        "address": "Sector 6, CDA, Cuttack, Odisha 753014, India",
        "phone": "+91 671 234 7700",
        "email": "info@kims.ac.in",
        "lat": 20.509857,
        "lng": 85.859853,
        "url": "https://www.kims.ac.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753014
      },
      {
        "name": "Sparsh Hospital",
        "address": "Plot No: B-14, Shreevihar, Chandrasekharpur, Bhubaneswar, Odisha 751016, India",
        "phone": "+91 674 274 2212",
        "email": "info@sparshhospital.com",
        "lat": 20.316861,
        "lng": 85.827588,
        "url": "https://sparshhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751016
      },
      {
        "name": "Kalinga Institute of Medical Sciences (KIMS)",
        "address": "KIIT Campus-5, Patia, Bhubaneswar, Odisha 751024, India",
        "phone": "+91 674 272 5606",
        "email": "info@kims.ac.in",
        "lat": 20.350682,
        "lng": 85.814474,
        "url": "https://kims.ac.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751024
      },
      {
        "name": "Ashwini Hospital",
        "address": "Bhubaneswar, Odisha 751014, India",
        "phone": "+91 674 254 1343",
        "email": "info@ashwinihospital.com",
        "lat": 20.3058565,
        "lng": 85.7972942,
        "url": "https://ashwinihospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751014
      },
      {
        "name": "Apollo Hospitals Cuttack",
        "address": "CDA, Sector - VI, Markat Nagar, Cuttack, Odisha 753014, India",
        "phone": "+91 671 235 8888",
        "email": "contactus@apollocuttack.com",
        "lat": 20.5006313,
        "lng": 85.8571768,
        "url": "https://www.apollocuttack.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753014
      },
      {
        "name": "Sparsh Hospital",
        "address": "Plot No: B-14, Shreevihar, Chandrasekharpur, Bhubaneswar, Odisha 751016, India",
        "phone": "+91 674 274 2212",
        "email": "info@sparshhospital.com",
        "lat": 20.316861,
        "lng": 85.827588,
        "url": "https://sparshhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751016
      },
      {
        "name": "Kar Clinic & Hospital",
        "address": "Plot No. 401, Khandagiri, Bhubaneswar, Odisha 751030, India",
        "phone": "+91 674 238 1427",
        "email": "karclinicbbsr@gmail.com",
        "lat": 20.2827693,
        "lng": 85.8078728,
        "url": "https://www.karclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751030
      },
      {
        "name": "Kalinga Institute of Dental Sciences",
        "address": "KIIT Deemed to be University, Patia, Bhubaneswar, Odisha 751024, India",
        "phone": "+91 674 272 5796",
        "email": "info@kids.ac.in",
        "lat": 20.350682,
        "lng": 85.814474,
        "url": "https://kids.ac.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751024
      },
      {
        "name": "Kar Clinic & Hospital",
        "address": "Plot No. 401, Khandagiri, Bhubaneswar, Odisha 751030, India",
        "phone": "+91 674 238 1427",
        "email": "karclinicbbsr@gmail.com",
        "lat": 20.2827693,
        "lng": 85.8078728,
        "url": "https://www.karclinic.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751030
      },
      {
        "name": "Neelachal Hospital Pvt. Ltd.",
        "address": "Sahid Nagar, Bhubaneswar, Odisha 751007, India",
        "phone": "+91 674 254 6832",
        "email": "info@neelachalhospital.com",
        "lat": 20.2935192,
        "lng": 85.8375844,
        "url": "https://www.neelachalhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751007
      },
      {
        "name": "Sun Hospital",
        "address": "Link Road, Cuttack, Odisha 753012, India",
        "phone": "+91 671 230 1333",
        "email": "info@sunhospital.com",
        "lat": 20.4691022,
        "lng": 85.8608598,
        "url": "https://www.sunhospital.com/",
        "country": "India",
        "state": "Odisha",
        "city": "Cuttack",
        "zip": 753012
      },
      {
        "name": "Apollo Hospitals Bhubaneswar",
        "address": "Plot No: 251, Sainik School Road, Bhubaneswar, Odisha 751005, India",
        "phone": "+91 674 666 1016",
        "email": "contactus@apollobbsr.com",
        "lat": 20.3142216,
        "lng": 85.8492954,
        "url": "https://www.apollohospitals.com/locations/india/bhubaneswar",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751005
      },
      {
        "name": "AIIMS Bhubaneswar",
        "address": "Sijua, Patrapada, Bhubaneswar, Odisha 751019, India",
        "phone": "+91 674 247 6789",
        "email": "director@aiimsbhubaneswar.edu.in",
        "lat": 20.2546233,
        "lng": 85.8166055,
        "url": "https://aiimsbhubaneswar.nic.in/",
        "country": "India",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "zip": 751019
      }
  ]
  